/**
 * Translations for english Language
 * (needs to be loaded after functions.js)
 */

Lang.setStrings({
   'RTR-NetTest': 'ČTÚ – NetTest',
   'Mbps' : 'Mb/s',
   'ms' : 'ms',
   'dBm' : 'dBm',
   'dB' : 'dB',
   'East' : 'E',
   'West' : 'W',
   'North' : 'N',
   'South' : 'S',
   'showMoreDevices' : 'Further devices',
   'AndroidAppAvailable' : 'If you would like to use the test to the full extent, please use our <a href="https://play.google.com/store/apps/details?id=at.alladin.rmbt.android&hl=en">Android-App</a>.',
   'IOSAppAvailable' : 'If you would like to use the test to the full extent, please use our <a href="https://itunes.apple.com/at/app/rtr-netztest/id724321403">iOS-App</a>.',
   'NoJavaAvailable' : 'A simple JavaScript test is carried out.',
   'BrowserOutdated' : 'Your browser version is outdated and does not support all necessary features. Please use a newer browser version.',
   'YourPostalCode' : 'Your postal code',
   'PostalCode' : 'Post code',
   'PleaseEnterPostalCode' : 'For optimum results please enter your post code.',
   'OutsideAustria' : 'Outside Austria',
   'StreetAddress' : 'Street/House number',
   'Country' : 'Country',
   'City' : 'City',
   'AddressInput' : 'optional, manual address entry',
   'PrivacyStatement' : 'Privacy statement',
   'PrivacyStatementLink' : 'https://www.rtr.at/en/tk/netztestprivacypolicy',
   'AustrianPostalCode' : 'Austrian postcode',
   'gkz': 'Austrian community ID',
   'community': 'Community',
   'locality': 'Cadastral community',
   'district': 'District',
   'province': 'Province',
   'Cancel' : 'Cancel',
   'Continue' : 'Continue',
   'clickToEdit' : 'click to edit',
   'MeasurementResultFrom' : 'Výsledky měření z',
   'TestResult' : 'Test result',
   'YourSyncCode' : 'Your synchronisation code is',
   'History' : 'Verlauf',
   'allOperators' : 'All operators',
   'countries' : {'eu': 'Europe', 'af': 'Afghanistan', 'al': 'Albania', 'dz': 'Algeria', 'as': 'American Samoa', 'ad': 'Andorra', 'ao': 'Angola', 'ai': 'Anguilla', 'aq': 'Antarctica', 'ag': 'Antigua and Barbuda', 'ar': 'Argentina', 'am': 'Armenia', 'aw': 'Aruba', 'au': 'Australia', 'at': 'Austria', 'az': 'Azerbaijan', 'bs': 'Bahamas', 'bh': 'Bahrain', 'bd': 'Bangladesh', 'bb': 'Barbados', 'by': 'Belarus', 'be': 'Belgium', 'bz': 'Belize', 'bj': 'Benin', 'bm': 'Bermuda', 'bt': 'Bhutan', 'bo': 'Bolivia, Plurinational State of', 'bq': 'Bonaire, Sint Eustatius and Saba', 'ba': 'Bosnia and Herzegovina', 'bw': 'Botswana', 'bv': 'Bouvet Island', 'br': 'Brazil', 'io': 'British Indian Ocean Territory', 'bn': 'Brunei Darussalam', 'bg': 'Bulgaria', 'bf': 'Burkina Faso', 'bi': 'Burundi', 'kh': 'Cambodia', 'cm': 'Cameroon', 'ca': 'Canada', 'cv': 'Cape Verde', 'ky': 'Cayman Islands', 'cf': 'Central African Republic', 'td': 'Chad', 'cl': 'Chile', 'cn': 'China', 'cx': 'Christmas Island', 'cc': 'Cocos (Keeling) Islands', 'co': 'Colombia', 'km': 'Comoros', 'cg': 'Congo', 'cd': 'Congo, the Democratic Republic of the', 'ck': 'Cook Islands', 'cr': 'Costa Rica', 'ci': 'Côte d’Ivoire', 'hr': 'Croatia', 'cu': 'Cuba', 'cw': 'Curaçao', 'cy': 'Cyprus', 'cz': 'Czech Republic', 'dk': 'Denmark', 'dj': 'Djibouti', 'dm': 'Dominica', 'do': 'Dominican Republic', 'ec': 'Ecuador', 'eg': 'Egypt', 'sv': 'El Salvador', 'gq': 'Equatorial Guinea', 'er': 'Eritrea', 'ee': 'Estonia', 'et': 'Ethiopia', 'fk': 'Falkland Islands (Malvinas)', 'fo': 'Faroe Islands', 'fj': 'Fiji', 'fi': 'Finland', 'fr': 'France', 'gf': 'French Guiana', 'pf': 'French Polynesia', 'tf': 'French Southern Territories', 'ga': 'Gabon', 'gm': 'Gambia', 'ge': 'Georgia', 'de': 'Germany', 'gh': 'Ghana', 'gi': 'Gibraltar', 'gr': 'Greece', 'gl': 'Greenland', 'gd': 'Grenada', 'gp': 'Guadeloupe', 'gu': 'Guam', 'gt': 'Guatemala', 'gg': 'Guernsey', 'gn': 'Guinea', 'gw': 'Guinea-Bissau', 'gy': 'Guyana', 'ht': 'Haiti', 'hm': 'Heard Island and McDonald Islands', 'va': 'Holy See (Vatican City State)', 'hn': 'Honduras', 'hk': 'Hong Kong', 'hu': 'Hungary', 'is': 'Iceland', 'in': 'India', 'id': 'Indonesia', 'ir': 'Iran, Islamic Republic of', 'iq': 'Iraq', 'ie': 'Ireland', 'im': 'Isle of Man', 'il': 'Israel', 'it': 'Italy', 'jm': 'Jamaica', 'jp': 'Japan', 'je': 'Jersey', 'jo': 'Jordan', 'kz': 'Kazakhstan', 'ke': 'Kenya', 'ki': 'Kiribati', 'kp': 'Korea, Democratic Peoples Republic of', 'kr': 'Korea, Republic of', 'kw': 'Kuwait', 'kg': 'Kyrgyzstan', 'la': 'Lao Peoples Democratic Republic', 'lv': 'Latvia', 'lb': 'Lebanon', 'ls': 'Lesotho', 'lr': 'Liberia', 'ly': 'Libya', 'li': 'Liechtenstein', 'lt': 'Lithuania', 'lu': 'Luxembourg', 'mo': 'Macao', 'mk': 'Macedonia, The Former Yugoslav Republic of', 'mg': 'Madagascar', 'mw': 'Malawi', 'my': 'Malaysia', 'mv': 'Maldives', 'ml': 'Mali', 'mt': 'Malta', 'mh': 'Marshall Islands', 'mq': 'Martinique', 'mr': 'Mauritania', 'mu': 'Mauritius', 'yt': 'Mayotte', 'mx': 'Mexico', 'fm': 'Micronesia, Federated States of', 'md': 'Moldova, Republic of', 'mc': 'Monaco', 'mn': 'Mongolia', 'me': 'Montenegro', 'ms': 'Montserrat', 'ma': 'Morocco', 'mz': 'Mozambique', 'mm': 'Myanmar', 'na': 'Namibia', 'nr': 'Nauru', 'np': 'Nepal', 'nl': 'Netherlands', 'nc': 'New Caledonia', 'nz': 'New Zealand', 'ni': 'Nicaragua', 'ne': 'Niger', 'ng': 'Nigeria', 'nu': 'Niue', 'nf': 'Norfolk Island', 'mp': 'Northern Mariana Islands', 'no': 'Norway', 'om': 'Oman', 'pk': 'Pakistan', 'pw': 'Palau', 'ps': 'Palestine, State of', 'pa': 'Panama', 'pg': 'Papua New Guinea', 'py': 'Paraguay', 'pe': 'Peru', 'ph': 'Philippines', 'pn': 'Pitcairn', 'pl': 'Poland', 'pt': 'Portugal', 'pr': 'Puerto Rico', 'qa': 'Qatar', 're': 'Réunion', 'ro': 'Romania', 'ru': 'Russian Federation', 'rw': 'Rwanda', 'bl': 'Saint Barthélemy', 'sh': 'Saint Helena, Ascension and Tristan da Cunha', 'kn': 'Saint Kitts and Nevis', 'lc': 'Saint Lucia', 'mf': 'Saint Martin (French part)', 'pm': 'Saint Pierre and Miquelon', 'vc': 'Saint Vincent and the Grenadines', 'ws': 'Samoa', 'sm': 'San Marino', 'st': 'Sao Tome and Principe', 'sa': 'Saudi Arabia', 'sn': 'Senegal', 'rs': 'Serbia', 'sc': 'Seychelles', 'sl': 'Sierra Leone', 'sg': 'Singapore', 'sx': 'Sint Maarten (Dutch part)', 'sk': 'Slovakia', 'si': 'Slovenia', 'sb': 'Solomon Islands', 'so': 'Somalia', 'za': 'South Africa', 'gs': 'South Georgia and the South Sandwich Islands', 'ss': 'South Sudan', 'es': 'Spain', 'lk': 'Sri Lanka', 'sd': 'Sudan', 'sr': 'Suriname', 'sj': 'Svalbard and Jan Mayen', 'sz': 'Swaziland', 'se': 'Sweden', 'ch': 'Switzerland', 'sy': 'Syrian Arab Republic', 'tw': 'Taiwan, Province of China', 'tj': 'Tajikistan', 'tz': 'Tanzania, United Republic of', 'th': 'Thailand', 'tl': 'Timor-Leste', 'tg': 'Togo', 'tk': 'Tokelau', 'to': 'Tonga', 'tt': 'Trinidad and Tobago', 'tn': 'Tunisia', 'tr': 'Turkey', 'tm': 'Turkmenistan', 'tc': 'Turks and Caicos Islands', 'tv': 'Tuvalu', 'ug': 'Uganda', 'ua': 'Ukraine', 'ae': 'United Arab Emirates', 'gb': 'United Kingdom', 'us': 'United States', 'um': 'United States Minor Outlying Islands', 'uy': 'Uruguay', 'uz': 'Uzbekistan', 'vu': 'Vanuatu', 've': 'Venezuela, Bolivarian Republic of', 'vn': 'Viet Nam', 'vg': 'Virgin Islands, British', 'vi': 'Virgin Islands, U.S.', 'wf': 'Wallis and Futuna', 'eh': 'Western Sahara', 'ye': 'Yemen', 'zm': 'Zambia', 'zw': 'Zimbabwe'},
   'invalidUUID' : 'invalid UUID',
   'decimalSeperator'   : '.',
   'thousandsSeperator' : ' ',
   'implausibleResult': 'Comment: Implausible test result. Test is ignored.',
   'NDTTestFailed': 'NDT-Test failed',
   'NDTTestFinished': 'NDT-Test finished',
   'CourseOverview': 'Course overview',
   'seconds_abbreviation': 's',
   'meters_abbreviation': 'm',
   'showAdditionalInformation' : 'Zobrazit další informace ...',
   'Measurement' : 'Measurement',
   'Net' : 'Net',
   'moreInfo' : 'More Info',
   'smallView': 'small view',
   'largeView': 'large view',
   'baseLayer' : 'Base layer',
   'Skip' : 'Skip',
   'basemap_bmapgrau': 'Basemap.at - grey',
   'basemap_geolandbasemap': 'Basemap.at - standard',
   'basemap_bmaphidpi': 'Basemap.at - high dpi',
   'basemap_bmaporthofoto30cm': 'Basemap.at - satellite',
   'map_dateformat' : 'D.M.YYYY, hh:mm:ss', //http://momentjs.com/docs/#/displaying/
   'map_index_dateformat' : 'hh:mm:ss',
   'all' : 'All',

   //fields from controlserver-resource
   'time': 'Čas testu',
   'timezone': 'Časová zóna',
   'ping_shortest': 'Doba odezvy (Ping)',
   'speed_upload': 'Rychlost vkládání (Upload)',
   'speed_download': 'Rychlost stahování (Download)',
   'signal_strength': 'Síla signálu',
   'network_type': 'Typ sítě',
   'country_location': 'Země lokality',
   'country_asn': 'Země',
   'country_geoip': 'IP země',
   'zip_code': 'PSČ',
   'wifi_ssid': 'WLAN SSID',
   'wifi_bssid': 'WLAN BSSID',
   'network_operator_name': 'Network (display)',
   'network_name': 'Network (display)',
   'network_operator': 'Mobilní sítě',
   'network_sim_operator_name': 'Domácí síť (název)',
   'network_sim_operator': 'Domácí síť',
   'roaming': 'Roaming',
   'total_bytes': 'Data amount RMB-Test',
   'total_if_bytes': 'Data amount interface',
   'test_if_bytes_download': 'Data if_dl',
   'test_if_bytes_upload': 'Data if_ul',
   'testdl_if_bytes_download': 'Data if_dl (dl-test)',
   'testdl_if_bytes_upload': 'Data if_ul (dl-test)',
   'testul_if_bytes_download': 'Data if_dl (ul-test)',
   'testul_if_bytes_upload': 'Data if_ul (ul-test)',
   'client_name': 'Název programu',
   'client_type': 'RMBT typ',
   'client_version': 'RMBT verze',
   'client_software_version': 'Verze program',
   'plattform': 'Platforma',
   'os_version': 'Verze platformy',
   'model': 'Model',
   'client_local_ip': 'Interní IP ',
   'client_public_ip': 'Externí IP',
   'client_public_ip_as_name': 'IP název sítě',
   'client_public_ip_as': 'IP síť (AS název)',
   'client_public_ip_rdns': 'Hostname',
   'provider_name': 'Operátor',
   'nat_type': 'NAT status',
   'location': 'Lokace',
   'motion': 'Motion',
   'server_name': 'Testovací server',
   'server_ip': 'Testserver IP',
   'server_location_name': 'Testserver location',
   'port': 'Testserver port',
   'encryption': 'RMBT encryption',
   'encryption_false': 'No',
   'encryption_true': 'Yes',
   'duration': 'Doba testu',
   'num_threads': 'Paralelní připojení pro stahování',
   'num_threads_ul': 'Paralelní připojení pro vkládání',
   'uuid': 'Test ID',
   'open_test_uuid': 'ID testu',
   'time_dl_ns': 'Start time download',
   'time_ul_ns': 'Start time upload',
   'speed_download_ndt': 'Download (NDT)',
   'speed_upload_ndt': 'Upload (NDT)',
   'ping_ndt': 'Latency (NDT)',
   'ndt_details_main': 'Details NDT (main)',
   'ndt_details_stat': 'Details NDT (stat)',
   'ndt_details_diag': 'Details NDT (diag)',
   'speed': 'Speed',
   'bearing': 'Bearing',
   'altitude': 'Altitude',
   'timing_advance': 'Timing Advance',

   //values not in the controlserver resource file
   'cat_technology': 'Typ připojení',
   'country_sim': 'SIM home country',
   'platform': 'Platform',
   'ip_anonym': 'IP (anonymized)',
   'open_uuid': 'Open-User-UUID',
   'network_country': 'Country of network',
   'distance': 'Movement',
   'lte_rsrp' : 'Signal strength (RSRP)',
   'lte_rsrq' : 'Signal quality (RSRQ)',
   'referenced_signal_received_quality': 'Reference signal received quality',

    //new attributes by DZ and attributes previously not displayed
    'model_native': 'Model (původní)',
    'ndt_download_kbit': 'NDT-data rate download',
    'ndt_upload_kbit': 'NDT-data rate upload',
    'time_ul_ms': 'Rel. start upload',
    'time_dl_ms': 'Rel. start download',
    'roaming_type': 'Roaming status',
    'wifi_link_speed': 'WLAN rychlost připojení',
    'asn': 'AS číslo',
    'num_threads_requested': 'Požadovaná připojení',
    'sim_mcc_mnc': 'Home network MCC-MNC',
    'duration_download_ms': 'Doba trvání stahování',
    'duration_upload_ms': 'Doba trvání vkladní',
    'network_mcc_mnc': 'Mobilní síť MCC-MNC',
    'bytes_download': 'Velikost stažených dat',
    'bytes_upload': 'Velikost vložených dat',
    'bytes' : 'bytes',
    'KB' : 'KB',
    'MB' : 'MB',
    'public_ip_as_name': 'IP název sítě',

    'roaming_international' : 'international roaming',
    'roaming_national' : 'national roaming',
    'roaming_none' : 'not roaming',

    'pleaseSelect' : 'Prosím vyberte',
    'addressNotFound' : 'Adresu se nepodařilo najít',


    //Test
    'Locating': 'Vyhledávání',
    'Initializing' : 'Inicializace',
    'WaitForSlot' : 'Čekání na testovací slot',
    'Init_Upload' : 'Nahrávání',
    // 'Ping' : 'Doba odezvy (ping)',
    'Download' : 'Rychlost stahování (download)',
    'Upload' : 'Rychlost vkládání (upload)',
    'Down': 'Down',
    'Up': 'Up',
    'Mio_abbr': 'm',
    'Thou_abbr': 'k',
    'Finished' : 'Dokončeno',
    'Error' : 'Chyba',
    'Aborted' : 'Přerušeno',
    'ErrorOccuredDuringTest' : 'Během testu došlo k chybě.<br />Zkuste to prosím znovu!',
    'PrematureEnd' : 'Test byl přerušen. Zkuste to prosím znovu!',
    'AppletCouldNotBeLoaded' : 'Java Applet could not be initialized.<br />Please check your Java installation: <a href="http://www.java.com/de/download/testjava.jsp">http://www.java.com/de/download/testjava.jsp</a>',
    'ErrorOnInitializingApplet' : 'Error on initializing the applet',
    'VerlaufHash' : '/cs/Verlauf#',
    'Init_applet' : 'Init applet',
    'NoPermission'  : 'Nedostatečné oprávnění',
    'NotAvailable' : 'Nedostupné',
    'NotSupported' : 'Nepodporováno',
    'DownloadPhase' : 'Fáze stahování',
    'UploadPhase' : 'Fáze vkládání',
    'Successful' : 'Úspěšné',
    'NDT' : 'NDT',
    'Failure' : 'Selhání',
    'details' : 'detaily',
    'NoOperatorsFound' : 'Pro aktuální výběr nebyli nalezeni žádní operátoři',
    'NoDevicesFound' : 'Pro aktuální výběr nebyla nalezena žádná zařízení',
    'QosTest' : 'Kvalita služeb',
    'FastConnectionWarning' : 'Due to technical limitations of the used test type, deviations are possible. If you suspect that the results are inaccurate, please conduct a test using the <a href="https://www.rtr.at/en/tk/rtrnetztest_tests">Android/iOS-App</a>.',
    'CheckConnection': "Zkontrolujte prosím své připojení k internetu",
    'TestsInTheLastXHours' : 'tests in the last % hours',
    'TestsInTheLastXMinutes' : 'tests in the last % minutes',
    'NoUUID' : 'You do not have an UUID',
    'SafariBroken' : 'Please use <a href="https://www.mozilla.org/de/firefox/new/">Mozilla Firefox</a> or <a href="https://www.google.de/chrome/browser/desktop/">Google Chrome</a> for performing the test. More infos are given <a href="https://www.rtr.at/de/tk/netztestfaq_web_100">in the FAQ</a>.',
    'FirefoxBroken' : 'Currently, the RTR-NetTest cannot be used with Firefox 82.0. Please use a different browser for the time being.',
    'LoopMode' : 'Opakované měření',
    'LoopModeTestsFinished' : 'Všechny testy jsou dokončeny',
    'LoopModeFinished' : 'Měření dokončena',
    'WaitingForStart' : 'Čekejte',
    'radio_band': 'Rádiové pásmo',
    'channel_number': 'Frekvenční kanál',
    'DontAskAgain': 'Neptejte se znovu',
    'CancelTest': 'Zrušit právě probíhající měření?',

    //corine land covers
    'corine_100':'Artificial surfaces',
    'corine_110':'Urban fabric',
    'corine_111':'Continuous urban fabric',
    'corine_112':'Discontinuous urban fabric',
    'corine_120':'Industrial, commercial and transport units',
    'corine_121':'Industrial or commercial units',
    'corine_122':'Road and rail networks and associated land',
    'corine_123':'Port areas',
    'corine_124':'Airports',
    'corine_130':'Mine, dump and construction sites',
    'corine_131':'Mineral extraction sites',
    'corine_132':'Dump sites',
    'corine_133':'Construction sites',
    'corine_140':'Artificial non-agricultural vegetated areas',
    'corine_141':'Green urban areas',
    'corine_142':'Sport and leisure facilities',
    'corine_200':'Agricultural areas',
    'corine_210':'Arable land',
    'corine_211':'Non-irrigated arable land',
    'corine_212':'Permanently irrigated land',
    'corine_213':'Rice fields',
    'corine_220':'Permanent crops',
    'corine_221':'Vineyards',
    'corine_222':'Fruit trees and berry plantations',
    'corine_223':'Olive groves',
    'corine_230':'Pastures',
    'corine_231':'Pastures',
    'corine_240':'Heterogeneous agricultural areas',
    'corine_241':'Annual crops associated with permanent crops',
    'corine_242':'Complex cultivation patterns',
    'corine_243':'Land principally occupied by agriculture, with significant areas of natural vegetation',
    'corine_244':'Agro-forestry areas',
    'corine_300':'Forests and semi-natural areas',
    'corine_310':'Forests',
    'corine_311':'Broad-leaved forest',
    'corine_312':'Coniferous forest',
    'corine_313':'Mixed forest',
    'corine_320':'Shrub and/or herbaceous vegetation association',
    'corine_321':'Natural grassland',
    'corine_322':'Moors and heathland',
    'corine_323':'Sclerophyllous vegetation',
    'corine_324':'Transitional woodland shrub',
    'corine_330':'Open spaces with little or no vegetation',
    'corine_331':'Beaches, dunes, and sand plains',
    'corine_332':'Bare rock',
    'corine_333':'Sparsely vegetated areas',
    'corine_334':'Burnt areas',
    'corine_335':'Glaciers and perpetual snow',
    'corine_400':'Wetlands',
    'corine_410':'Inland wetlands',
    'corine_411':'Inland marshes',
    'corine_412':'Peatbogs',
    'corine_420':'Coastal wetlands',
    'corine_421':'Salt marshes',
    'corine_422':'Salines',
    'corine_423':'Intertidal flats',
    'corine_500':'Water bodies',
    'corine_510':'Inland waters',
    'corine_511':'Water courses',
    'corine_512':'Water bodies',
    'corine_520':'Marine waters',
    'corine_521':'Coastal lagoons',
    'corine_522':'Estuaries',
    'corine_523':'Sea and ocean',
    'land_cover': 'Land cover',
    'land_cover_cat1': 'Land cover (category)',
    'land_cover_cat2': 'Land cove (subcategory)',
    'link_id': 'Street link ID',
    'link_name': 'Street identifier',
    'link_distance': 'Street distance',
    'edge_id': 'Street edge ID',
    'link_name1': 'Street name1',
    'link_name2': 'Street name2',
    'link_frc': 'Street category',
    'settlement_type': 'Settlement type',
    'settlement_type_1':'No settlement area',
    'settlement_type_2':'Habitable area',
    'settlement_type_3':'Settlement area',
    'dtm_level': 'DTM level',
    'enter_first_name': 'Zadejte křestní jméno.',
    'enter_last_name': 'Zadejte příjmení.',
    'enter_provider_name': 'Zadejte název poskytovatele služby',
    'enter_provider_service_name': 'Zadejte název služby',
    'enter_provider_contract_number': 'Zadejte číslo smlouvy',
    'download_results_as_pdf': 'Stáhnout výsledky ve formátu PDF',
    'alert_close_tab': 'Do you want to cancel the measurement?',
    'help': 'Nápověda'
});
